---
version: "3"
networks:
  private_network:
    ipam:
      driver: default
      config:
        - subnet: 10.2.0.0/24

services:
  unbound:
    image: mvance/unbound:latest
    container_name: unbound
    hostname: unbound
    volumes:
      - unbound:/opt/unbound/etc/unbound
    networks:
      private_network:
        ipv4_address: 10.2.0.10

  adguard:
    image: adguard/adguardhome
    container_name: adguard
    hostname: adguard
    volumes:
      - adguard-work:/opt/adguardhome/work
      - adguard-conf:/opt/adguardhome/conf
    networks:
      private_network:
        ipv4_address: 10.2.0.11
    depends_on:
      - unbound

  wireguard:
    image: lscr.io/linuxserver/wireguard:latest
    container_name: wireguard
    hostname: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=994
      - TZ=Europe/Amsterdam
      - SERVERPORT=51820
      - PEERS=1
      - PEERDNS=10.2.0.11
      - INTERNAL_SUBNET=10.69.0.0/24
      - ALLOWED_IPS=0.0.0.0/0
      - LOG_CONFS=false
    volumes:
      - wireguard:/config
      - /lib/modules:/lib/modules
    networks:
      private_network:
        ipv4_address: 10.2.0.12
    ports:
      - 51820:51820/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped
    depends_on:
      - unbound
      - adguard

volumes:
  unbound:
  adguard-work:
  adguard-conf:
  wireguard:
